### ISSUE TITLE
Improve build experience

### ISSUE THREAD

**Issue by robinbb** [LeapYear/inline-java#1]
Improve the build experience for the 'jni' and 'jvm' packages on Mac and Linux. Docker my be required for this, and Nix may be used, also.

**Comment by robinbb** [comment]
Please also handle packages on which these packages depend, such as `thread-local-storage`.

**Comment by facundominguez** [comment]
IIUC inline-java requires ghc 8.0.2 or ghc HEAD to work which the sparkle configuration doesn't use at the moment. Shall we change the milestone of this task?

Note that jni and jvm install fine when following sparkle build instructions.

**Comment by robinbb** [comment]
The 'inline-java' package requires GHC 8.0.2 or GHC HEAD, but the 'jni' and 'jvm' packages do not. It would be nice if they were able to be built independently of 'inline-java'. Note that I am not advocating creating separate repos for 'jni' and 'jvm'. But, it would be nice if they could be built using 'stack', separately from 'inline-java'. This may be necessary in the near future in case we want to address memory management issues in any of 'jni', 'jvm', or 'thread-local-storage'.

**Comment by robinbb** [comment]
Taking this issue from you, @facundominguez, since I have begun work on it. I'll continue with it.
